SET(Pcre_FOUND FALSE)

INCLUDE (CheckIncludeFiles)
INCLUDE (CheckLibraryExists) 
INCLUDE(FindPackageHandleStandardArgs)

CHECK_INCLUDE_FILES(pcre.h HAVE_PCRE_H) 
CHECK_LIBRARY_EXISTS(pcre pcre_compile "" HAVE_PCRE) 

IF (HAVE_PCRE_H AND HAVE_PCRE)
    
    SET(PCRE_INCLUDE_DIR "" )
    SET(PCRE_LIBRARIES pcre)
    
    SET(Pcre_FOUND TRUE)
ELSE (HAVE_PCRE_H AND HAVE_PCRE)
    FIND_PROGRAM(PCRE_CONFIG NAMES pcre-config )
    SET(Pcre_FOUND FALSE)
ENDIF (HAVE_PCRE_H AND HAVE_PCRE)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Pcre DEFAULT_MSG Pcre_FOUND)

